<a href="https://colab.research.google.com/github/ponjagannath/DataScienceAndML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **numpy one dimensional array**

In [3]:
my_list = [1,2,3,4,5]
import numpy as np
np.array(my_list)

array([1, 2, 3, 4, 5])

# **numpy two dimensional array** 

In [ ]:
my_mat = [[1,2,3],
          [4,5,6],
          [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# ***arange, zeros, ones- to generate numbers***

In [ ]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros((5,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# **linspace**

In [ ]:
#generates 100 elements between 1 to 5
np.linspace(1,5,100)

array([1.        , 1.04040404, 1.08080808, 1.12121212, 1.16161616,
       1.2020202 , 1.24242424, 1.28282828, 1.32323232, 1.36363636,
       1.4040404 , 1.44444444, 1.48484848, 1.52525253, 1.56565657,
       1.60606061, 1.64646465, 1.68686869, 1.72727273, 1.76767677,
       1.80808081, 1.84848485, 1.88888889, 1.92929293, 1.96969697,
       2.01010101, 2.05050505, 2.09090909, 2.13131313, 2.17171717,
       2.21212121, 2.25252525, 2.29292929, 2.33333333, 2.37373737,
       2.41414141, 2.45454545, 2.49494949, 2.53535354, 2.57575758,
       2.61616162, 2.65656566, 2.6969697 , 2.73737374, 2.77777778,
       2.81818182, 2.85858586, 2.8989899 , 2.93939394, 2.97979798,
       3.02020202, 3.06060606, 3.1010101 , 3.14141414, 3.18181818,
       3.22222222, 3.26262626, 3.3030303 , 3.34343434, 3.38383838,
       3.42424242, 3.46464646, 3.50505051, 3.54545455, 3.58585859,
       3.62626263, 3.66666667, 3.70707071, 3.74747475, 3.78787879,
       3.82828283, 3.86868687, 3.90909091, 3.94949495, 3.98989

# **Identity matrix**

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# **Random number**

In [4]:
np.random.rand(5)

array([0.52154234, 0.45866616, 0.13478653, 0.99052761, 0.62285612])

In [5]:
np.random.randn(5)

array([ 2.09834959, -1.01168909,  0.74225852,  1.07508976, -1.06989458])

In [6]:
np.random.randn(4,4)

array([[ 0.4987824 ,  1.9232836 ,  0.27327712,  1.84956093],
       [ 1.30940305,  0.90481381,  0.99210739, -1.61004833],
       [ 0.46528767, -0.17219381, -1.78996478,  0.63951799],
       [-0.43509184, -0.34861442, -0.52631557, -0.59050219]])

In [11]:
arr = np.random.randint(10,100,20)
arr

array([12, 45, 54, 23, 70, 96, 15, 77, 67, 50, 26, 21, 42, 82, 19, 96, 74,
       47, 95, 85])

# **Reshape**

In [12]:
arr.reshape(4,5)

array([[12, 45, 54, 23, 70],
       [96, 15, 77, 67, 50],
       [26, 21, 42, 82, 19],
       [96, 74, 47, 95, 85]])

# **Min, Max**

In [14]:
arr.max()

96

In [15]:
arr.min()

12

In [16]:
#index location of the max value
arr.argmax()

5

In [17]:
#index location of the min value
arr.argmin()

0

# **shape of the array**

In [19]:
arr.shape

(20,)

# **data type of the array**

In [20]:
arr.dtype

dtype('int64')