<a href="https://colab.research.google.com/github/ponjagannath/DataScienceAndML/blob/master/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **numpy one dimensional array**

In [5]:
my_list = [1,2,3,4,5]
import numpy as np
np.array(my_list)

array([1, 2, 3, 4, 5])

# **numpy two dimensional array** 

In [3]:
my_mat = [[1,2,3],
          [4,5,6],
          [7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# **arange - to generate numbers**

In [6]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])